//
// Created by hubert25632 on 27.04.22.
//

#ifndef MPPT_CONTROLLER_FIRMWARE_MPPTCAN_HPP
#define MPPT_CONTROLLER_FIRMWARE_MPPTCAN_HPP

#include "CanParser_autogenerated.hpp"
#include "CommCAN.hpp"
#include "MpptCom.hpp"

using namespace SBT::System::Comm;

class MpptCAN : public SBT::System::PeriodicTask {
    std::shared_ptr<MpptCom> const mpptCom;

    const CAN_ID::Source canSourceID;
    PV_DATA_t pvData{};
    MPPT_CHARGER_DATA_t chargerData{};
    YIELD_DATA_t yieldData{};
    uint8_t canPayload[8];

    std::array<VEDirectParser::ParameterID, 0>::const_iterator paramIter;
    unsigned cycleCounter;

public:
    explicit MpptCAN(std::shared_ptr<MpptCom> mpptCom,
                     CAN_ID::Source canSourceID);
    void initialize() override;
    void run() override;
};

#endif // MPPT_CONTROLLER_FIRMWARE_MPPTCAN_HPP
